# Generated by Django 4.1.1 on 2022-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernamePasswordKeeperApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='platform',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='user_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
