# Generated by Django 4.1.1 on 2022-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='your_todo',
            field=models.CharField(max_length=100),
        ),
    ]
